name: Fantasma Digital Automatizado

on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:

jobs:
  ejecutar-fantasma:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar codigo del repositorio
        uses: actions/checkout@v4

      - name: Configurar entorno de Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Instalar dependencias
        run: pip install requests

      - name: Ejecutar motor fantasma
        run: |
          echo "Despertando al fantasma en la nube..."
          python motor_maestro.py
        env:
          FB_ACCESS_TOKEN: ${{ secrets.FB_ACCESS_TOKEN }}
